// players
globalvar PLAYER1, PLAYER2;
PLAYER1 = 0
PLAYER2 = 1

// packet types from server
globalvar OBJ_CREATE, OBJ_CREATE_SPEED_DIR, OBJ_POS, OBJ_DESTROY, SOUND_PLAY, EFFECT_CREATE;
OBJ_CREATE = 0
OBJ_CREATE_SPEED_DIR = 1
PLAYER_POS = 2
OBJ_DESTROY = 3
SOUND_PLAY = 4
EFFECT_CREATE = 5

// packet types to server
globalvar INPUT;
INPUT = 0

// object types
globalvar OBSTACLE, FLAG, BULLET;
OBSTACLE = 0
FLAG = 1
BULLET = 2
